# Generated by Django 3.2.6 on 2021-08-30 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
