# Generated by Django 3.2.6 on 2021-09-07 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210830_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='height',
            field=models.FloatField(default='1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='width',
            field=models.FloatField(default='1.1'),
            preserve_default=False,
        ),
    ]
