# Generated by Django 3.2.6 on 2021-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210907_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
