# Generated by Django 3.2.6 on 2021-09-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_videos_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
