# Generated by Django 3.2.6 on 2021-09-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Queries', 'verbose_name_plural': 'Queries'},
        ),
    ]
